[project]
name = "rubiks-cube-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kociemba>=1.2.1",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "ruff>=0.9.7",
]
